version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:7860"
    volumes:
      - ./server/data:/app/server/data
    environment:
      - SECRET_KEY=nong-san-bi-mat-2026
      - DATABASE_URL=sqlite:///./server/data/nongsan.db
      - HF_HOME=/app/server/data/hf_cache
    restart: always

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
    restart: always
